spring.application.name=auth-server

#http://localhost:8080/.well-known/openid-configuration
#http://localhost:8080/oauth2/authorize?response_type=code&client_id=DS001&redirect_uri=http://localhost:8081&scope=openid

#curl -u "DS001:secret" -H "Content-Type: application/x-www-form-urlencoded" -X POST http://localhost:8080/oauth2/token -d "client_id=DS001&grant_type=authorization_code&code=C7nKoKgj42Kz0I2c8Ek4UwF8EAfphvnkYu0mJgHpGT6dgmc7UwJ1s8Gh23W3SXfumjRTPxn2S4hYdnyWxRJOZ62IYcwbKiukCUFecXgIzv5-p55V5z4saawRw1LeM-rx&redirect_uri=http://localhost:8081"
